steps:

- id: npm-install
  name: gcr.io/cloud-builders/npm:node-10.3.0
  args: ['ci']

- id: npm-run-test
  name: gcr.io/cloud-builders/npm:node-10.3.0
  args: ['run','test']

- id: npm-run-coverage
  name: gcr.io/cloud-builders/npm:node-10.3.0
  args: ['run','coverage']

timeout: 5m

tags: ['${REPO_NAME}', '${BRANCH_NAME}']

artifacts:
  objects:
    location: 'gs://gitzup-build-artifacts/${REPO_NAME}/${COMMIT_SHA}'
    paths: ['dist']
